apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::328342418911:role/eksctl-expense-nodegroup-ng-NodeInstanceRole-yBmaXcQ12XNT
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::328342418911:user/test
      username: test
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-20T08:35:32Z"
  name: aws-auth
  namespace: kube-system
  uid: de87fbf8-fc10-4591-a498-f8385edc1a36 #don't delete this.
